-- subscriptions definition

CREATE TABLE subscriptions (
	CLINIC_ID VARCHAR(50),
	STRIPE_SUBSCRIPTION_ID VARCHAR(50),
	SUBSCRIPTION_START_DATE date,
	SUBSCRIPTION_END_DATE date,
	SUBSCRIPTION_CURRENT_PERIOD_STARTED_AT timestamp,
	SUBSCRIPTION_CURRENT_PERIOD_ENDS_AT timestamp,
	MOST_RECENT_INVOICE_CREATED_AT timestamp,
	LAST_PAYMENT_AT timestamp,
	CHECKOUT_STATUS VARCHAR(50),
	SUBSCRIPTION_STATUS VARCHAR(50),
	BILLING_INTERVAL_IN_MONTHS INTEGER,
	FIRST_PAYMENT_METHOD_TYPE VARCHAR(50),
	FIRST_CARD_BRAND VARCHAR(50),
	FIRST_PAYMENT_AMOUNT decimal(5,2),
	FIRST_PAYMENT_AMOUNT_OFF decimal(5,2),
	FIRST_PAYMENT_PROMOTION_CODE VARCHAR(50),
	FIRST_PAYMENT_COUPON_ID VARCHAR(50),
	FIRST_PAYMENT_AMOUNT_OFF_2 VARCHAR(50)
);